//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFBusiness.NfseWSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="NfseWSService.NfseWSServiceSoap")]
    public interface NfseWSServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (GerarNfseRequest) da mensagem GerarNfseRequest não corresponde ao valor padrão (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        NFBusiness.NfseWSService.GerarNfseResponse GerarNfse(NFBusiness.NfseWSService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.GerarNfseResponse> GerarNfseAsync(NFBusiness.NfseWSService.GerarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (CancelarNfseRequest) da mensagem CancelarNfseRequest não corresponde ao valor padrão (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        NFBusiness.NfseWSService.CancelarNfseResponse CancelarNfse(NFBusiness.NfseWSService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.CancelarNfseResponse> CancelarNfseAsync(NFBusiness.NfseWSService.CancelarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (SubstituirNfseRequest) da mensagem SubstituirNfseRequest não corresponde ao valor padrão (SubstituirNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        NFBusiness.NfseWSService.SubstituirNfseResponse SubstituirNfse(NFBusiness.NfseWSService.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.SubstituirNfseResponse> SubstituirNfseAsync(NFBusiness.NfseWSService.SubstituirNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (RecepcionarLoteRpsSincronoRequest) da mensagem RecepcionarLoteRpsSincronoRequest não corresponde ao valor padrão (RecepcionarLoteRpsSincrono)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (RecepcionarLoteRpsRequest) da mensagem RecepcionarLoteRpsRequest não corresponde ao valor padrão (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        NFBusiness.NfseWSService.RecepcionarLoteRpsResponse RecepcionarLoteRps(NFBusiness.NfseWSService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(NFBusiness.NfseWSService.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarLoteRpsRequest) da mensagem ConsultarLoteRpsRequest não corresponde ao valor padrão (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        NFBusiness.NfseWSService.ConsultarLoteRpsResponse ConsultarLoteRps(NFBusiness.NfseWSService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(NFBusiness.NfseWSService.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfseServicoPrestadoRequest) da mensagem ConsultarNfseServicoPrestadoRequest não corresponde ao valor padrão (ConsultarNfseServicoPrestado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfseServicoTomadoRequest) da mensagem ConsultarNfseServicoTomadoRequest não corresponde ao valor padrão (ConsultarNfseServicoTomado)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfsePorFaixaRequest) da mensagem ConsultarNfsePorFaixaRequest não corresponde ao valor padrão (ConsultarNfsePorFaixa)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfsePorRpsRequest) da mensagem ConsultarNfsePorRpsRequest não corresponde ao valor padrão (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequest() {
        }
        
        public GerarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class GerarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse() {
        }
        
        public GerarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequest() {
        }
        
        public CancelarNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class CancelarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse() {
        }
        
        public CancelarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfseRequest() {
        }
        
        public SubstituirNfseRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubstituirNfseResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class SubstituirNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponse() {
        }
        
        public SubstituirNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincronoRequest() {
        }
        
        public RecepcionarLoteRpsSincronoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincronoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsSincronoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponse() {
        }
        
        public RecepcionarLoteRpsSincronoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequest() {
        }
        
        public RecepcionarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse() {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequest() {
        }
        
        public ConsultarLoteRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse() {
        }
        
        public ConsultarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestadoRequest() {
        }
        
        public ConsultarNfseServicoPrestadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoPrestadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoPrestadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponse() {
        }
        
        public ConsultarNfseServicoPrestadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomadoRequest() {
        }
        
        public ConsultarNfseServicoTomadoRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseServicoTomadoResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfseServicoTomadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponse() {
        }
        
        public ConsultarNfseServicoTomadoResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequest() {
        }
        
        public ConsultarNfsePorFaixaRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorFaixaResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorFaixaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponse() {
        }
        
        public ConsultarNfsePorFaixaResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nfseCabecMsg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequest() {
        }
        
        public ConsultarNfsePorRpsRequest(string nfseCabecMsg, string nfseDadosMsg) {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://nfse.abrasf.org.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse() {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfseWSServiceSoapChannel : NFBusiness.NfseWSService.NfseWSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfseWSServiceSoapClient : System.ServiceModel.ClientBase<NFBusiness.NfseWSService.NfseWSServiceSoap>, NFBusiness.NfseWSService.NfseWSServiceSoap {
        
        public NfseWSServiceSoapClient() {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseWSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseWSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.GerarNfseResponse NFBusiness.NfseWSService.NfseWSServiceSoap.GerarNfse(NFBusiness.NfseWSService.GerarNfseRequest request) {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.GerarNfseRequest inValue = new NFBusiness.NfseWSService.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.GerarNfseResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.GerarNfseResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.GerarNfseAsync(NFBusiness.NfseWSService.GerarNfseRequest request) {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.GerarNfseRequest inValue = new NFBusiness.NfseWSService.GerarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).GerarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.CancelarNfseResponse NFBusiness.NfseWSService.NfseWSServiceSoap.CancelarNfse(NFBusiness.NfseWSService.CancelarNfseRequest request) {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.CancelarNfseRequest inValue = new NFBusiness.NfseWSService.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.CancelarNfseResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.CancelarNfseResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.CancelarNfseAsync(NFBusiness.NfseWSService.CancelarNfseRequest request) {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.CancelarNfseRequest inValue = new NFBusiness.NfseWSService.CancelarNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.SubstituirNfseResponse NFBusiness.NfseWSService.NfseWSServiceSoap.SubstituirNfse(NFBusiness.NfseWSService.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfse(request);
        }
        
        public string SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.SubstituirNfseRequest inValue = new NFBusiness.NfseWSService.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.SubstituirNfseResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).SubstituirNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.SubstituirNfseResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.SubstituirNfseAsync(NFBusiness.NfseWSService.SubstituirNfseRequest request) {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.SubstituirNfseRequest inValue = new NFBusiness.NfseWSService.SubstituirNfseRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).SubstituirNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse NFBusiness.NfseWSService.NfseWSServiceSoap.RecepcionarLoteRpsSincrono(NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }
        
        public string RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest inValue = new NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).RecepcionarLoteRpsSincrono(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.RecepcionarLoteRpsSincronoAsync(NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest request) {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest inValue = new NFBusiness.NfseWSService.RecepcionarLoteRpsSincronoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.RecepcionarLoteRpsResponse NFBusiness.NfseWSService.NfseWSServiceSoap.RecepcionarLoteRps(NFBusiness.NfseWSService.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.RecepcionarLoteRpsRequest inValue = new NFBusiness.NfseWSService.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.RecepcionarLoteRpsResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.RecepcionarLoteRpsAsync(NFBusiness.NfseWSService.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.RecepcionarLoteRpsRequest inValue = new NFBusiness.NfseWSService.RecepcionarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.ConsultarLoteRpsResponse NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarLoteRps(NFBusiness.NfseWSService.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarLoteRpsRequest inValue = new NFBusiness.NfseWSService.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.ConsultarLoteRpsResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarLoteRpsResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarLoteRpsAsync(NFBusiness.NfseWSService.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarLoteRpsRequest inValue = new NFBusiness.NfseWSService.ConsultarLoteRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfseServicoPrestado(NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }
        
        public string ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest inValue = new NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfseServicoPrestado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfseServicoPrestadoAsync(NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest request) {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest inValue = new NFBusiness.NfseWSService.ConsultarNfseServicoPrestadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfseServicoTomado(NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }
        
        public string ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest inValue = new NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfseServicoTomado(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfseServicoTomadoAsync(NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest request) {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest inValue = new NFBusiness.NfseWSService.ConsultarNfseServicoTomadoRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfsePorFaixa(NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }
        
        public string ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest inValue = new NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfsePorFaixa(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfsePorFaixaAsync(NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest request) {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest inValue = new NFBusiness.NfseWSService.ConsultarNfsePorFaixaRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfsePorRps(NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest inValue = new NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse retVal = ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse> NFBusiness.NfseWSService.NfseWSServiceSoap.ConsultarNfsePorRpsAsync(NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NFBusiness.NfseWSService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg) {
            NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest inValue = new NFBusiness.NfseWSService.ConsultarNfsePorRpsRequest();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((NFBusiness.NfseWSService.NfseWSServiceSoap)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
    }
}
